### ISSUE TITLE
Zsh vi-mode cursor not working well

### ISSUE THREAD

**Issue by g6ai** [g6ai/dotfiles#5]

**Comment by g6ai** [comment]
These are not working well:
https://github.com/g6ai/dotfiles/blob/f908b21286078c30d4da0b5fc5f2b782cf0fde1a/zsh/zshrc#L14-L33

And oh-my-zsh plugin [zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode) conflicts with autosuggestions settings.

Suprisingly, the official [vi-mode](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vi-mode) plugin by oh-my-zsh works well.

**Comment by g6ai** [comment]
Use vi-mode and zsh-vi-mode in conjunction! It takes advantage of both plugins. See https://github.com/g6ai/dotfiles/commit/3f914eeb6fe7fecf4284d9b9199abf4af3840d8e.

**Comment by jeffreytse** [comment]
Hi @g6ai 

Could you tell me about the zsh-vi-mode's conflicts with autosuggestions settings?

Thanks and regards

**Comment by g6ai** [comment]
Hi @jeffreytse, thanks for making the amazing plugin!

With zsh-vi-mode enabled, this zsh-autosuggestions setting:
https://github.com/g6ai/dotfiles/blob/275ba75df6a1f93b01d2525ae63a90929400dd24/zsh/zshrc#L19
is not working, specifically I cannot use ctrl-space to complete autosuggestions. I can only use the default right-arrow key to complete.

Somehow to include the vi-mode plugin together with zsh-vi-mode solves this issue...

**Comment by jeffreytse** [comment]
Hi @g6ai 

Could you open an issue and submit this to the repository's issue page? It will be helpful for other people who also met this issue. And I will focus on this issue and fix it as soon as possible.

Thanks and regards

**Comment by g6ai** [comment]
Sure!

**Comment by g6ai** [comment]
The solution is https://github.com/jeffreytse/zsh-vi-mode/issues/57#issuecomment-799364881
